In [1]:
import pandas as pd
import numpy as np

In [8]:
cols = ['IDnumber','Diagnosis','radius','texture','perimeter'
        ,'area','smoothness','compactness','concavity','concave_points','symmetry','fractal_dimension']
df = pd.read_csv('data/breast-cancer-wisconsin.data', names=cols)

In [9]:
df.head()

,IDnumber,Diagnosis,radius,texture,perimeter,area,smoothness,compactness,concavity,concave_points,symmetry,fractal_dimension
0,1000025,5,1,1,1,2,1,3,1,1,2,NaN
1,1002945,5,4,4,5,7,10,3,2,1,2,NaN
2,1015425,3,1,1,1,2,2,3,1,1,2,NaN
3,1016277,6,8,8,1,3,4,3,7,1,2,NaN
4,1017023,4,1,1,3,2,1,3,1,1,2,NaN

In [23]:
df['Diagnosis'].unique()

array([ 5,  3,  6,  4,  8,  1,  2,  7, 10,  9])

In [13]:
df.isna().sum()

IDnumber               0
Diagnosis              0
radius                 0
texture                0
perimeter              0
area                   0
smoothness             0
compactness            0
concavity              0
concave_points         0
symmetry               0
fractal_dimension    699
dtype: int64

In [20]:
df = df.drop('fractal_dimension', axis=1)

In [21]:
df.head()

,IDnumber,Diagnosis,radius,texture,perimeter,area,smoothness,compactness,concavity,concave_points,symmetry
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2